### PR TITLE
#264 fix(notification): resolve 5 critical sound engine bugs

### LINKED ISSUE #264: Fix sound engine: Tokio crash, error handling, MP3 support, and sound rotation
## Description

Fix critical bugs in the notification sound engine introduced in PR #240. The PlaybackQueue crashes on startup because it spawns a Tokio task before the runtime is ready. Sound test errors are silently swallowed. MP3 support and sound rotation are missing.

## Requirements

- REQ-1: Lazy-initialize PlaybackQueue on first `notify()` call instead of during service construction (fixes Tokio runtime panic at `playback_queue.rs:60`)
- REQ-2: Make `test_notification_sound` Tauri command synchronous — return errors to frontend instead of swallowing them, show toast on failure
- REQ-3: Add `minimp3` feature to rodio in Cargo.toml for MP3 playback support (MIT licensed, no patent issues)
- REQ-4: Implement sound rotation — `HashMap<(EventType, PackId), usize>` in queue actor, random selection excluding last played sound
- REQ-5: Add `test_notification_sound` to `TAURI_ONLY_COMMANDS` in `mock_toast_bridge.ts` for browser mock mode

## Acceptance Criteria

- [ ] App starts without Tokio runtime panic — PlaybackQueue initializes lazily on first notification
- [ ] Clicking "Test Sound" in settings plays the sound and shows error toast if playback fails
- [ ] MP3 files play correctly when assigned to notification events
- [ ] When an event has multiple sounds, consecutive plays rotate randomly (never same sound twice in a row)
- [ ] In browser mock mode, `test_notification_sound` shows "Desktop app required" toast instead of silently failing

## Notes

- `playback_queue.rs:58-61` — the `tauri::async_runtime::spawn()` call happens before Tauri runtime exists
- `notification_commands.rs` — `test_notification_sound` spawns thread and returns `Ok(())` immediately
- Sound rotation needs ~15 lines in the queue actor
- Per-sound volume override table (`sound_volume_overrides`) already exists in schema

### PR DESCRIPTION
**Pull request by MartinoPolo**
## Description
- **Lazy PlaybackQueue initialization** — Wrapped PlaybackQueueHandle in LazyPlaybackQueue using OnceLock. Queue actor now spawns on first enqueue() call instead of during Tauri setup, preventing Tokio runtime panic.
- **Error surfacing** — Made test_notification_sound async with spawn_blocking. Playback errors now propagate to frontend; NotificationSettingsPanel displays danger toast on failure.
- **MP3 support** — Added minimp3 feature to rodio in Cargo.toml. MP3 files now decode and play correctly.
- **Sound rotation** — Implemented pick_sound_index with rotation map in queue actor. Service resolves all candidate sounds from pack manifest for event category. Consecutive plays never repeat the last-played sound.
- **Browser mock bridge** — Added test_notification_sound to TAURI_ONLY_COMMANDS and COMMAND_BODIES. Browser mode now shows "Desktop app required" toast.

## Resolves
Closes #264

## Testing
- [x] 4 new Rust tests added (lazy init, rotation indexing)
- [x] 1 new TypeScript test added (mock bridge toast)
- [x] Manual testing of sound playback with MP3 files

### CODE REVIEW

**Comment by MartinoPolo** [comment]
## Final Report — Issue #264

### Summary

Fixed 5 critical bugs in the notification sound engine introduced in PR #240.

### Changes

| REQ | Description | Files |
|-----|------------|-------|
| REQ-1 | Lazy-init PlaybackQueue via `OnceLock` — queue actor spawns on first `enqueue()` call, not during Tauri setup | `playback_queue.rs`, `lib.rs`, `service.rs` |
| REQ-2 | `test_notification_sound` is now async with `spawn_blocking` — errors propagate to frontend, danger toast on failure | `notification_commands.rs`, `NotificationSettingsPanel.svelte` |
| REQ-3 | Added `minimp3` feature to rodio for MP3 playback | `Cargo.toml` |
| REQ-4 | Sound rotation via `pick_sound_index` + rotation map in queue actor, pack-aware candidate resolution in service | `playback_queue.rs`, `service.rs` |
| REQ-5 | Added `test_notification_sound` to `TAURI_ONLY_COMMANDS` and `COMMAND_BODIES` | `tauri_mock.ts`, `mock_toast_bridge.ts` |

### Tests Added

- **Rust** (4 new): `lazy_playback_queue_creation_does_not_panic`, `pick_sound_index_single_candidate_returns_zero`, `pick_sound_index_excludes_last_played`, `pick_sound_index_no_exclusion_returns_valid_index`
- **TypeScript** (1 new): mock bridge shows toast for `test_notification_sound`

### CI

- All 511 Rust tests passed
- All 930 TypeScript tests passed
- Static checks (prettier + oxlint + fallow + svelte-check + eslint): all passed
- CI run: https://github.com/MartinoPolo/Grovekeeper/actions/runs/25606307752

### Review Findings

- Fixed `pick_from_candidates` empty-slice panic (changed return type to `Option<PathBuf>`)
- Pre-existing issues noted but not in scope: debounce logic duplication, volume loading duplication, default volume magic constant

### PR

https://github.com/MartinoPolo/Grovekeeper/pull/268
